Server:
  RunMode: release
  HttpPort: 16214     # 端口
  ReadTimeout: 30
  WriteTimeout: 30
Mysql:  # 正常使用无需开启
  Running: false
  Host: 127.0.0.1
  Port: 3306
  Username: user
  Password: passwd
  Database: db
Redis:
  Running: false
  Host: 127.0.0.1
  Port: 6379
  Auth: ""
  Database: 0
  IdleTimeout: 5    # 秒
  PoolSize: 100
  SubCacheTime: 15  # 分钟，订阅缓存时间
Log:
  Path: ./logs
  FilePrefix: tvh
  Encoder: json    # json/console
  Output: file     # both/file/console
  LumberJack:
    MaxSize: 1        # 在进行切割之前，日志文件的最大大小（以MB为单位）
    MaxBackups: 30    # 保留旧文件的最大个数
    MaxAge: 7         # 保留旧文件的最大天数
    Compress: true    # 是否压缩/归档旧文件
Spider:
  DouBanClientTimeout: 5000 # 毫秒
  AListClientTimeout: 5000 # 毫秒
  ParserClientTimeout: 5000 # 毫秒
AList:  # 正常使用无需开启
  Host: 127.0.0.1
  Token: token
